### PR TITLE
Sync with original repo

### PR DESCRIPTION
**Pull request by payamnj**
Hi,
I would like to contribute in translating the vue.js documents for the Persian language.
I've noticed that this repository is not updated since 2017 so this pull request is just a sync with the original repo and some minor style changes for RTL direction.

### CODE REVIEW

**Comment by payamnj** [comment]
@pi0 Hey, I have a kinda funny pull request here :)

**Comment by pi0** [comment]
Hey @payamnj. Sorry for late checking. I think we have to hard reset base to the origin.

**Comment by payamnj** [comment]
@pi0 make sense. So I will close this PR.

**Comment by pi0** [comment]
Repo updated @payamnj. I've also invited you to org. Please use pull-requests toward `fa` branch.

**Comment by payamnj** [comment]
Great :+1:  And thank you very much for inviting me :)

**Pull request closed without merging**
